name: Build, Push, and Deploy to ECS.

on:
  push:
    branches: [ "main", "dev" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_URI: 767397940350.dkr.ecr.ap-south-1.amazonaws.com/gts/gts_django 
  ECS_CLUSTER_NAME: gts-prod-cluster
  ECS_SERVICE_NAME: gts-django-task-service-main
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: gts-django-container
  IAM_ROLE_ARN: arn:aws:iam::767397940350:role/gts-django-git-ecs-deploy-role
  
permissions:
  id-token: write 
  contents: read  

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    environment: 
          name: ${{ github.ref == 'refs/heads/main' && 'production' || 'dev' }}
    
    steps:
      - name: Set Environment Variables
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
            echo "ECS_CLUSTER_NAME=gts-prod-cluster" >> $GITHUB_OUTPUT
            echo "ECS_SERVICE_NAME=gts-django-task-service-main" >> $GITHUB_OUTPUT
            echo "ECS_TASK_DEFINITION=task-definition.json" >> $GITHUB_OUTPUT

          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_OUTPUT
            echo "ECS_CLUSTER_NAME=gts-dev-cluster" >> $GITHUB_OUTPUT     
            echo "ECS_SERVICE_NAME=gts-django-service-dev" >> $GITHUB_OUTPUT 
            echo "ECS_TASK_DEFINITION=task-definition-dev.json" >> $GITHUB_OUTPUT
            
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          IMAGE_TAG=${{ steps.set-env.outputs.IMAGE_TAG }}
          docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
          docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
          echo "image=$ECR_REPOSITORY_URI:$IMAGE_TAG" >> $GITHUB_OUTPUT
          
      - name: Render new task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.set-env.outputs.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
          environment-variables: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DEBUG=${{ secrets.DEBUG }}
            ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}

      - name: Deploy new task definition to ECS
        id: deploy-task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ steps.set-env.outputs.ECS_SERVICE_NAME }}
          cluster: ${{ steps.set-env.outputs.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true